SCR_MissionHeader {
 World "{48F6DA5A8150BDD9}worlds/Sasha20k_pro/Big Boom Air Support/Big Boom Air Support.ent"
 m_sName "TVT (16-44) Big Boom Air Support"
 m_sAuthor "Sasha20k_pro"
 m_sDescription "Separatists Ambush an US Armored Column (With Air Support)"
 m_iPlayerCount 44
 m_iStartingHours 17
 m_GC_Metadata GC_MissionMetadata "{6A54807D93DA6205}" {
  m_FriendlyForce GC_ForceDefinition "{6A54807D921974A5}" {
   m_sFactionKey "RHS_USAF"
  }
  m_OpposingForce GC_ForceDefinition "{6A54807D8F607205}" {
   m_sFactionKey "GC_SEPARATISTS"
   m_eType MOTORIZED
  }
  m_eEra ERA_2020s
  m_eSpecialAssets {
   ATK_HELIS
  }
 }
}